
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-26T00:12:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ceda11fc43ce95ac63e77da1d0108aaee5d128a",
 "version": "4.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
